RIGHT           seek 5                                        #event:click
RIGHT           script-message-to evafast speedup             #event:press
RIGHT           script-message-to evafast slowdown            #event:release

TAB             script-message-to file_browser browse-files;script-message-to file_browser dynamic/reload;show-text '' #event:click
TAB             script-message-to uosc toggle-ui              #event:press
TAB             script-message-to uosc toggle-ui              #event:release

PGDWN           add chapter -1                                                               #event:click
PGDWN           playlist-prev;show-text 播放列表:${playlist-pos-1}/${playlist-count}         #event:click|chapter == 0
PGDWN           playlist-prev;show-text 播放列表:${playlist-pos-1}/${playlist-count}         #event:press
PGUP            add chapter  1                                                               #event:click
PGUP            playlist-next;show-text 播放列表:${playlist-pos-1}/${playlist-count}         #event:click|chapter+1 == chapters
PGUP            playlist-next;show-text 播放列表:${playlist-pos-1}/${playlist-count}         #event:press

SPACE           cycle pause;script-message-to uosc flash-pause-indicator  #event:click
SPACE           script-binding simplehistory/history-load-last            #event:click|idle_active
SPACE           no-osd set speed 3; set pause no                          #event:press
SPACE           ignore                                                    #event:release

MBTN_LEFT       cycle pause;script-message-to uosc flash-pause-indicator  #event:click
MBTN_LEFT       cycle fullscreen                                          #event:double_click
